package constants

const (
	FEATURE_ROBOT   = "robot"
	FEATURE_SERVICE = "service"
	FEATURE_APP     = "app"
	FEATURE_RUNTIME = "runtime"
	RUNNER_BIN      = "bin"
	RUNNER_PYTHON   = "python"
	RUNNER_SHELL    = "shell"
	ENV_ROOT        = "ROOT"
	ENV_IPC         = "IPC"
	ENV_ROOTPID     = "ROOT_PID"
	ENV_ADDR        = "ADDR"
	ENV_LISTEN_ADDR = "LISTENADDR"
	ENV_DUMPENV     = "DUMPENV"
	ENV_IPC_TCP     = "IPC_TCP"
	ENV_LOG         = "LOG"
	ENV_DEBUG_PROTO = "DEBUG_PROTO"
	ENV_PYTHON      = "PYTHON"
	ENV_HTTPBASE    = "HTTPBASE"
	ENV_STRAWID     = "STRAWID"

	IPC_CORE     = "core"
	IPC_SVC_CLIP = "clip"
	IPC_STATIC   = "static"
	IPC_DB       = "db"
	IPC_NOTIFY   = "notify"

	IPC_CORE_reg          = "reg"
	IPC_CORE_regs         = "regs"
	IPC_CORE_unreg        = "unreg"
	IPC_CORE_db_ConfigGet = "db.ConfigGet"
	IPC_CORE_db_MenuGet   = "db.MenuGet"
	IPC_CORE_db_QueueAdd  = "db.QueueAdd"

	BASE_URL          = "BASE_URL"
	ADDR              = "ADDR"
	PYTHON            = "PYTHON"
	SHELL             = "SHELL"
	ROOT              = "ROOT"
	LOGGING           = "LOGGING"
	RESTART           = "RESTART"
	CHECK_URL         = "CHECK_URL"
	ROBOT_ID          = "ROBOT_ID"
	OWNER             = "OWNER"
	SHOWCONSOLE       = "SHOWCONSOLE"
	UID               = "UID"
	VSCODE            = "VSCODE"
	SCRIPTS_ROOT      = "SCRIPTS_ROOT"
	REPOS_ROOT        = "REPOS_ROOT"
	STATIC_ROOT       = "STATIC_ROOT"
	AUTO_OPEN_CONSOLE = "AUTO_OPEN_CONSOLE"
	NOTIFY_ON_OPEN    = "NOTIFY_ON_OPEN"
	USE_TRAY          = "USE_TRAY"
	TEMP              = "TEMP"
	WORKINGIR         = "WORKINGIR"
	ADDONS_DIR        = "ADDONS_DIR"
	CHANNEL           = "CHANNEL"

	API_VERCHECK = "/api/vercheck"
	API_VERGET   = "/api/verget"

	EVT_TYPE_JOBSTART  = "jobstart"
	EVT_TYPE_JOBFINISH = "jobfinish"
	EVT_TYPE_APPSTART  = "appstart"
	EVT_TYPE_APPFINISH = "appfinish"

	ENV_REPLAY_INSTANCE_ALIAS = "REPLAY_INSTANCE_ALIAS"
	ENV_ROOT_PID              = "ROOT_PID"
	ENV_REPLAY_ADDR           = "REPLAY_ADDR"
	ENV_REPLAY_DATADIR        = "REPLAY_DATADIR"
	ENV_REPLAY_REPO           = "REPLAY_REPO"
	ENV_REPLAY_APIKEY         = "REPLAY_APIKEY"
	ENV_REPLAY_ALIAS          = "REPLAY_ALIAS"
	ENV_REPLAY_VER            = "REPLAY_VER"
	ENV_REPLAY_QUEUEID        = "REPLAY_QUEUEID"
)
